
version: 2.1
orbs:
  python: circleci/python@1.2

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: 
            pip install pytest
            pytest
  run: 
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - run:
          name: Run main
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt 
            python3 main.py 
            python3 main.py 
      
workflows:
  version: 2
  test:
    jobs:
      - build-and-test
      - run:
          context:
          - "todoist"
  nightly:
    triggers:
      - schedule:
          cron:  "0,15,30,48 * * * *"
          filters:
            branches:
              only:
                - main
                - circleci
    jobs:
      - build-and-test
      - run:
          context:
          - "todoist"